# Generated by Django 4.0.1 on 2022-01-20 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import paginas.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=128)),
                ('agencia', models.CharField(max_length=128)),
                ('conta', models.CharField(max_length=128, unique=True)),
                ('pix', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Autores',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=128, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('valor', models.FloatField()),
                ('categoria', models.CharField(max_length=128)),
                ('resolucao', models.CharField(max_length=128)),
                ('formato', models.CharField(max_length=128)),
                ('link', models.CharField(max_length=128)),
                ('arquivo', models.ImageField(upload_to=paginas.models.upload_image)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginas.autor')),
            ],
            options={
                'verbose_name_plural': 'Imagens',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('valor', models.FloatField()),
                ('duracao', models.IntegerField()),
                ('pix', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Planos',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Imagem_favorita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginas.imagem')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Imagens_favoritas',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=128)),
                ('numero', models.IntegerField(unique=True)),
                ('validade', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Cartoes',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Assinante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_inicio', models.DateField()),
                ('data_final', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginas.plano')),
            ],
            options={
                'verbose_name_plural': 'Assinantes',
                'ordering': ('created_at',),
            },
        ),
    ]
