# Generated by Django 4.0.1 on 2022-01-20 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='arquivo',
            field=models.ImageField(upload_to=''),
        ),
    ]
