# Generated by Django 4.0.1 on 2022-01-27 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paginas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='imagem_favorita',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AddField(
            model_name='imagem',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginas.autor'),
        ),
        migrations.AddField(
            model_name='imagem',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginas.categoria_imagem'),
        ),
        migrations.AddField(
            model_name='imagem',
            name='formato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginas.formato_imagem'),
        ),
        migrations.AddField(
            model_name='estudante',
            name='estabelecimento_de_ensino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginas.estabelecimento_de_ensino'),
        ),
        migrations.AddField(
            model_name='estudante',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginas.plano'),
        ),
        migrations.AddField(
            model_name='estudante',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='autor',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assinante',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginas.plano'),
        ),
        migrations.AddField(
            model_name='assinante',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
