# Generated by Django 4.0.1 on 2022-01-26 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudante',
            name='data_de_inicio',
        ),
    ]
