# Generated by Django 4.0.1 on 2022-01-20 00:58

from django.db import migrations, models
import paginas.models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0002_alter_imagem_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='arquivo',
            field=models.ImageField(upload_to=paginas.models.upload_image),
        ),
    ]
