# Generated by Django 4.0.1 on 2022-01-28 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paginas', '0003_alter_imagem_favorita_imagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem_favorita',
            name='imagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginas.imagem'),
        ),
        migrations.AlterField(
            model_name='imagem_favorita',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='imagem_favorita',
            constraint=models.UniqueConstraint(fields=('usuario', 'imagem'), name='unica_img'),
        ),
    ]
