# Generated by Django 4.0.1 on 2022-01-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0003_remove_estudante_data_de_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='pix',
            field=models.CharField(blank=True, max_length=128, unique=True),
        ),
    ]
