# Generated by Django 4.0.1 on 2022-01-28 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0004_alter_imagem_favorita_imagem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formato_imagem',
            options={'ordering': ('created_at',), 'verbose_name_plural': 'Formato_imagens'},
        ),
    ]
